# Generated by Django 2.2.16 on 2022-09-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Добавьте иллюстрацию к посту. Необязательное поле', upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
